.nh
.TH "HUGO-CONVERT" "1" "Aug 2025" "Hugo 0.147.9" "Hugo Manual"

.SH NAME
hugo-convert - Convert front matter to another format


.SH SYNOPSIS
\fBhugo convert [command] [flags]\fP


.SH DESCRIPTION
Convert front matter to another format.

.PP
See convert's subcommands toJSON, toTOML and toYAML for more information.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for convert

.PP
\fB-o\fP, \fB--output\fP=""
	filesystem path to write files to

.PP
\fB--unsafe\fP[=false]
	enable less safe operations, please backup first


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--clock\fP=""
	set the clock used by Hugo, e.g. --clock 2021-11-06T22:30:00.00+09:00

.PP
\fB--config\fP=""
	config file (default is hugo.yaml|json|toml)

.PP
\fB--configDir\fP="config"
	config dir

.PP
\fB-d\fP, \fB--destination\fP=""
	filesystem path to write files to

.PP
\fB-e\fP, \fB--environment\fP=""
	build environment

.PP
\fB--ignoreVendorPaths\fP=""
	ignores any _vendor for module paths matching the given Glob pattern

.PP
\fB--logLevel\fP=""
	log level (debug|info|warn|error)

.PP
\fB--noBuildLock\fP[=false]
	don't create .hugo_build.lock file

.PP
\fB--quiet\fP[=false]
	build in quiet mode

.PP
\fB-M\fP, \fB--renderToMemory\fP[=false]
	render to memory (mostly useful when running the server)

.PP
\fB-s\fP, \fB--source\fP=""
	filesystem path to read files relative from

.PP
\fB--themesDir\fP=""
	filesystem path to themes directory


.SH SEE ALSO
\fBhugo(1)\fP, \fBhugo-convert-toJSON(1)\fP, \fBhugo-convert-toTOML(1)\fP, \fBhugo-convert-toYAML(1)\fP
